config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :comments
  end
  resources :workouts
  resources :personals

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	validates :title, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :comments
	
	validates :title, presence: true, length: { minimum: 5 }

    validates :category, presence: true

    validates :preptime, presence: true

    validates :ingredients, presence: true, length: {minimum: 5}

    validates :directions, presence: true, length: {minimum: 5}								      

end

app/models/workout.rb
class Workout < ActiveRecord::Base
	validates :body, presence: true

	validates :date, presence: true

	validates :log, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.create(comment_params)
		redirect_to recipe_path(@recipe)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
	http_basic_authenticate_with name: "shaddy", password: "sz636302", except: [:index, :show]

	def index
		@personals = Personal.all.order('created_at DESC')
	end

	def show
		@personal = Personal.find(params[:id])
	end


	def new
		@personal = Personal.new
	end

	def edit
		@personal = Personal.find(params[:id])
	end

	def create
		@personal = Personal.new(personal_params)

		if @personal.save
			redirect_to @personal
		else
			render 'new'
		end
	end

	def update
  		@personal = Personal.find(params[:id])
 
  		if @personal.update(personal_params)
    		redirect_to @personal
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@personal = Personal.find(params[:id])
  		@personal.destroy
 
  		redirect_to personals_path
	end

	private
		def personal_params
			params.require(:personal).permit(:title, :text)
		end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
	    @recipe = Recipe.all
	  end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
 
  		if @recipe.save
  			redirect_to @recipe
  		else
  			render 'new'
  		end	
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy

		redirect_to recipes_path
	end

	private
  		def recipe_params
    		params.require(:recipe).permit(:title, :category, :preptime, :ingredients, :directions, :calories, :fats, :carbs, :protein)
  		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

	http_basic_authenticate_with name: "shaddy", password: "sz636302", except: [:index, :show]

	def index
		@workouts = Workout.all.order('created_at DESC')
	end

	def show
		@workout = Workout.find(params[:id])
	end

	def new
		@workout = Workout.new
	end

	def edit
		@workout = Workout.find(params[:id])
	end

	def create
		@workout = Workout.new(workout_params)

		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def update
  		@workout = Workout.find(params[:id])
 
  		if @workout.update(workout_params)
    		redirect_to @workout
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@workout = Workout.find(params[:id])
  		@workout.destroy
 
  		redirect_to workouts_path
	end

	private
		def workout_params
			params.require(:workout).permit(:body, :date, :log, :user)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">EVOCATIV</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to ' Home', root_path %></li>
        <!--<li><%= link_to ' All workouts', controller: 'workouts' %></li>-->
        <li><%= link_to ' All Workouts', controller: 'workouts' %></li>

        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">A days <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to ' Lower a', controller: 'workouts', :view => "lowera" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Upper a', controller: 'workouts', :view => "uppera" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Legs a', controller: 'workouts', :view => "legsa" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Push a', controller: 'workouts', :view => "pusha" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Pull a', controller: 'workouts', :view => "pulla" %></li>

          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">B days <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to ' Lower b', controller: 'workouts', :view => "lowerb" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Upper b', controller: 'workouts', :view => "upperb" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Legs b', controller: 'workouts', :view => "legsb" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Push b', controller: 'workouts', :view => "pushb" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' Pull b', controller: 'workouts', :view => "pullb" %></li>

          </ul>
        </li>
        <li><%= link_to ' View PRs', controller: 'personals' %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        
        <li class><%= link_to 'New PR', new_personal_path %></li>
        <li class><%= link_to 'Log a Workout', new_workout_path %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EVOCATIV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personals/index.html.erb
<%= render :partial => 'layouts/topnav'%>
<style>
body{
  background-image: url("wall.png");
  }

</style>

<div class="container">
<h1>Showing all PRs</h1>
 
<table class = "table table-hover">
  <tr>
    <th>Body Part</th>
    <th>Weight</th>
  </tr>
  <% @personals.each do |personal| %>
    <tr>
      <td><%= personal.title %></td>
      <td><%= personal.text %></td>
      <td><%= link_to 'Destroy', personal_path(personal),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>
</div>

app/views/personals/new.html.erb
<%= render :partial => 'layouts/topnav'%>

<style>
ul
{
    list-style-type: none;
}
</style>
<div class="container">
<h1>New PR</h1>

<%= form_for :personal, url: personals_path do |f| %>

<% if @personal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@personal.errors.count, "error") %> prohibited
        this personal from being saved:
      </h2>
      <ul>
        <% @personal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="jumbotron">
 <h3>Body Part:</h3>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit "Save personal", class: "btn btn-default btn-lg" %>
  </p>


<% end %>
</div>  
</div>

app/views/personals/show.html.erb
<%= render :partial => 'layouts/topnav'%>
<div class="container">
<div class="jumbotron">
<p>
  <strong>Body Part:</strong>
  <%= @personal.title %>
</p>
 
 <p>
  <strong>Lift:</strong>
  <%= @personal.text %>
</p>

<br>
<br>
<br>
<br>
 <p><%= link_to 'Back', personals_path %></p>
 </div>
 </div>

app/views/recipes/index.html.erb
<%= render :partial => 'layouts/topnav'%>
<style>
body{
  background-image: url("wall.png");
  }
</style>
<div class="container">
<h1>Listing Recipes</h1>

<table class = "table table-hover">
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Preptime</th>
    <th>Display</th>
  </tr>
<%if (params[:view] == "shaddyAdmin")%>
  <% @recipe.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.preptime %></td>
        <td><%= link_to 'Destroy', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <%end%>
 <%else%>      
  <% @recipe.each do |recipe| %>
  <% if(params[:view] == "breakfast")%>
    <% if  (recipe.category == "breakfast") %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.preptime %></td>
        <td><%= link_to 'Show', recipe_path(recipe) %></td>
      </tr>
      <%end%>
  <%elsif (params[:view] == "lunch")%>
    <% if recipe.category == "lunch" %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.preptime %></td>
        <td><%= link_to 'Show', recipe_path(recipe) %></td>
      </tr>
    <%end%>
  <%elsif (params[:view] == "dinner")%>
    <% if recipe.category == "dinner" %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.preptime %></td>
        <td><%= link_to 'Show', recipe_path(recipe) %></td>
      </tr>
    <%end%>  
  <%elsif (params[:view] == "snack")%>
    <% if recipe.category == "snack" %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= recipe.category %></td>
      <td><%= recipe.preptime %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
    </tr>  
    <%end%>
  <%else%>
    <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.preptime %></td>
        <td><%= link_to 'Show', recipe_path(recipe) %></td>
    </tr>
  <%end%>
  <% end %>
  <%end%>
</table>
</div>

app/views/recipes/new.html.erb
<%= render :partial => 'layouts/topnav'%>
<style>
body{
  background-image: url("wall.png");
  }

</style>

<div class="container">
<h2>Submit a Recipe!</h2>

<%= form_for :recipe, url: recipes_path do |f| %>
<!--Error Checking-->
<div>
<% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h3>
      <ul >
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>



<form>
<div class="jumbotron"> 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title , class: 'form-control', placeholder: "Enter Title"%>
  </p>
 
 <p>Please select a category:</p>
  <table class ="table table-striped">

  	<td>
   	<%= f.radio_button :category, 'breakfast' %>
  	<%= label :category_breakfast, 'Breakfast' %>
  	</td>
  	<td>
  	<%= f.radio_button :category, 'lunch' %>
  	<%= label :category_lunch, 'Lunch' %>
  	</td>
  	<td>
  	<%= f.radio_button :category, 'dinner' %>
  	<%= label :category_dinner, 'Dinner' %>
  	</td>
  	<td>
  	<%= f.radio_button :category, 'snack' %>
  	<%= label :category_snack, 'Snack' %>
  	</td>
  </table>

  <p>
    <%= f.label :preptime %><br>
    <%= f.text_field :preptime, class: 'form-control', placeholder: "Enter Preptime" %>  </p>

  <p>
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients, class: 'form-control', placeholder: "Enter Ingredients List" %>
  </p>

  <p>
    <%= f.label :directions %><br>
   	<%= f.text_area :directions, class: 'form-control', placeholder: "Enter Directions" %>
  </p>

  <p>Optional:</p>
  <p>
    <%= f.label :calories %><br>
    <%= f.text_field :calories, class: 'form-control', placeholder: "Calories" %>
  </p>

  <p>
    <%= f.label :fats %><br>
    <%= f.text_field :fats, class: 'form-control', placeholder: "Enter Fats" %>
  </p>

  <p>
    <%= f.label :carbs %><br>
   	<%= f.text_field :carbs , class: 'form-control', placeholder: "Enter Carbs"%>
  </p>

  <p>
    <%= f.label :protein %><br>
    <%= f.text_field :protein , class: 'form-control', placeholder: "Enter Protein"%>  </p>

  <p>
    <%= f.submit "Submit Recipe", class: "btn btn-default"%>
  </p>
<% end %>
</div>
</form>
</div>

app/views/recipes/show.html.erb
<%= render :partial => 'layouts/topnav'%>

<div class = "container">
<h1><%=@recipe.title%></h1>
<div class="jumbotron">
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
	<strong>Category:</strong>
	<%= @recipe.category %>
</p>

<p>
	<strong>Preptime:</strong>
  	<%= @recipe.preptime %>
</p>

<p>
	<strong>Ingredients:</strong>
  	<%= @recipe.ingredients %>
</p>

<p>
	<strong>Directions:</strong>
  	<%= @recipe.directions %>
</p>
 
<!--Checking For Nutritional Information-->

<% if @recipe.calories != '' %>
 <p>
	<strong>Calories:</strong>
  	<%= @recipe.calories %>
</p>
<%end%>


<% if @recipe.fats != '' %>
<p>
	<strong>Fats:</strong>
  	<%= @recipe.fats %>
</p>
<%end%>

<% if @recipe.carbs != '' %>
<p>
	<strong>Carbs:</strong>
  	<%= @recipe.carbs %>
</p>
<%end%>

<% if @recipe.protein != '' %>
<p>
	<strong>Protein:</strong>
  	<%= @recipe.protein %>
</p>
<%end%>
</div>

<!--Comments Section -->
<h2>Comments</h2>
<% @recipe.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<!--Adding a Comment-->
<h2>Add a comment:</h2>
<%= form_for([@recipe, @recipe.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

</div>

app/views/welcome/index.html.erb
<%= render :partial => 'layouts/topnav'%>

<style>
body{
	background-image: url("wall.png");
	}
</style>



 <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="jumbotron">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">EVOCATIV
                    <small>Work towards a better you.</small>
                </h1>
            </div>
        </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                <img class="img-responsive" src="http://endlessnovel.com/wp-content/uploads/motivational-quotes-bodybuilding-4.jpg" alt="">
            </div>

            <div class="col-md-4">
                <h3>Favorites:</h3>
                <div class="list-group">
  					<a href="https://www.youtube.com/user/Machiavelli929/videos?shelf_id=1&view=0&sort=dd" class="list-group-item">Motivational Videos</a>
  					<a href="http://forum.bodybuilding.com/" class="list-group-item">Bodybuilding Forum</a>
  					<a href="https://www.reddit.com/r/Fitness/" class="list-group-item">Fitness Reddit</a>
            </div>

        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shaddy Zayour</p>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->
</div>

app/views/workouts/edit.html.erb
<%= render :partial => 'layouts/topnav'%>

<style>
ul
{
    list-style-type: none;
}
</style>
<div class="container">
<h1>Editing Workout</h1>

<%= form_for :workout, url: workout_path(@workout), method: :patch do |f| %>

<% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workout.errors.count, "error") %> prohibited
        this workout from being saved:
      </h2>
      <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="jumbotron">
 <h3>Body Part:</h3>
  <table class ="table table-striped">
  	<td>
  		<%= f.radio_button :body, 'Lower a' %>
  		<%= label :body_lowera, 'Lower A' %>
  	</td>
  	<td>
   		<%= f.radio_button :body, 'Upper a' %>
  		<%= label :body_uppera, 'Upper A' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Legs a' %>
  		<%= label :body_legsa, 'Legs A' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Push a' %>
  		<%= label :body_pusha, 'Push A' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Pull a' %>
  		<%= label :body_pulla, 'Pull A' %>
  	</td>
  </table>

  <table class ="table table-striped">
  	<td>
  		<%= f.radio_button :body, 'Lower b' %>
  		<%= label :body_lowerb, 'Lower B' %>
  	</td>
  	<td>
   		<%= f.radio_button :body, 'Upper b' %>
  		<%= label :body_upperb, 'Upper B' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Legs b' %>
  		<%= label :body_legsb, 'Legs B' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Push b' %>
  		<%= label :body_pushb, 'Push B' %>
  	</td>
  	<td>
  		<%= f.radio_button :body, 'Pull b' %>
  		<%= label :body_pullb, 'Pull B' %>
  	</td>
  </table>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, class: 'form-control', placeholder: "mm/dd/yy" %>
  </p>
 
  <p>
    <%= f.label :log %><br>
    <%= f.text_area :log, class: 'form-control', placeholder: "Enter Workout" %>
  </p>
 
  <p>
    <%= f.submit "Save Workout", class: "btn btn-default btn-lg" %>
  </p>

<%= link_to 'Back', workouts_path %>
<% end %>
</div>  
</div>

app/views/workouts/index.html.erb
<%= render :partial => 'layouts/topnav'%>
<style>
body{
  background-image: url("wall.png");
  }

</style>

<div class="container">
<h1>Showing all Workouts</h1>
 
<table class = "table table-hover">
  <tr>
    <th>Body Part</th>
    <th>Date</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  <% @workouts.each do |workout| %>
<!--A Split-->  
  <% if(params[:view] == "legsa")%>
    <% if  (workout.body == "Legs a") %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "lowera")%>
    <% if workout.body == "Lower a" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "uppera")%>
    <% if workout.body == "Upper a" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "pusha")%>
    <% if workout.body == "Push a" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "pulla")%>
    <% if workout.body == "Pull a" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>  
<!--B split-->
     <%elsif(params[:view] == "legsb")%>
    <% if  (workout.body == "Legs b") %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "lowerb")%>
    <% if workout.body == "Lower b" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "upperb")%>
    <% if workout.body == "Upper b" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "pushb")%>
    <% if workout.body == "Push b" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>

  <%elsif (params[:view] == "pullb")%>
    <% if workout.body == "Pull b" %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <% end %>  

    <% else %>
    <tr>
      <td><%= workout.body %></td>
      <td><%= workout.date %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
    <%end%>
  <% end %>
</table>
</div>

app/views/workouts/show.html.erb
<%= render :partial => 'layouts/topnav'%>
<div class="container">
<div class="jumbotron">
<p>
  <strong>Body Part:</strong>
  <%= @workout.body %>
</p>
 
 <p>
  <strong>Date:</strong>
  <%= @workout.date %>
</p>

<p>
  <strong>Log:</strong>
  <%= simple_format(@workout.log) %>
</p>

<br>
<br>
<br>
<br>
 <p><%= link_to 'Edit', edit_workout_path(@workout) %>
 <%= link_to 'Back', workouts_path %></p>
 </div>
 </div>